# General settings
title: Liste Laut
email: kontakt@laut-bochum.de
description: >- 
  Die Liste Laut ist eine Wahlliste an der Ruhr-Universität Bochum voller toller Leute.
logo: "/assets/images/LAUT-Logo.png"
masthead_title: "LAUT"
baseurl: "/"
url: "https://laut-bochum.de"
github_username: liste-laut-bochum
repository: "liste-laut-bochum/liste-laut-bochum.github.io"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache

minimal_mistakes_skin: "contrast"
locale: "de"
lang: "de"
